logger:
  level: "info"

database:
  address:
    - "postgres:localdb@postgres:5432/nakama"
  conn_max_lifetime_ms: 0
  max_open_conns: 0
  max_idle_conns: 100

runtime:
  path: "/nakama/data/modules"
